---
- name: Chrony | configure | Enable Chrony service on system startup
  become: true
  ansible.builtin.service:
    name: "{{ __chrony_service_name }}"
    enabled: true
  when: >
    chrony_service_enabled | default(false)

- name: Chrony | configure | Disable Chrony service on system startup
  become: true
  ansible.builtin.service:
    name: "{{ __chrony_service_name }}"
    enabled: false
  when: >
    not chrony_service_enabled | default(false)

- name: Chrony | configure | Deploy Chrony configuration file
  become: true
  ansible.builtin.template:
    src: "chrony/chrony.conf.j2"
    dest: "{{ __chrony_config_path }}"
    mode: "0644"
    owner: root
    group: root
    backup: true
  # chrony does not provide a built-in config validation command (like nginx -t)
  notify: restart chrony

- name: Chrony | configure | Ensure log directory exists
  become: true
  ansible.builtin.file:
    path: "{{ chrony_logdir_path }}"
    state: directory
    mode: "0750"
    group: "{{ __chrony_log_directory_user }}"
    owner: "{{ __chrony_log_directory_user }}"
