---
# =============================================================================
# Ansible Role: Chrony - Tasks: Logrotate
# =============================================================================
# Configure logrotate for Chrony logs.
# =============================================================================

- name: Chrony | logrotate | Ensure archive log directory exists
  become: true
  ansible.builtin.file:
    path: "{{ chrony_logrotate_options.archive_directory_path }}"
    state: directory
    mode: "0750"
    owner: "{{ __chrony_log_directory_user }}"
    group: "{{ __chrony_log_directory_user }}"
  when: >
    chrony_logrotate_options.archive_directory_path is defined and
    chrony_logrotate_options.archive_directory_path | length > 0


- name: Chrony | logrotate | Deploy logrotate configuration file
  become: true
  ansible.builtin.template:
    src: "logrotate/chrony.j2"
    dest: "{{ __chrony_logrotate_config_path }}"
    owner: root
    mode: "0644"
    backup: true
