---
# Main task orchestrator for the Chrony role.
# Tags are prefixed with chrony_ per Red Hat CoP §3.1.4.

- name: Chrony | include_vars | Gather OS specific variables
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_facts['distribution'] | lower }}_{{ ansible_facts['distribution_version'] | lower }}.yml"
        - "{{ ansible_facts['distribution'] | lower }}_{{ ansible_facts['distribution_major_version'] | lower }}.yml"
        - "{{ ansible_facts['distribution'] | lower }}.yml"
        - "{{ ansible_facts['os_family'] | lower }}_{{ ansible_facts['distribution_version'] | lower }}.yml"
        - "{{ ansible_facts['os_family'] | lower }}_{{ ansible_facts['distribution_major_version'].split('.')[0] }}.yml"
        - "{{ ansible_facts['os_family'] | lower }}.yml"
        - "main.yml"
      paths:
        - "{{ role_path }}/vars"
  tags:
    - always
    - chrony_setup
    - chrony_init

- name: Chrony | assert | Validate role variables and requirements
  ansible.builtin.include_tasks: assert.yml
  run_once: true
  tags:
    - always
    - chrony_validate

- name: Chrony | prerequisites | Verify system prerequisites
  ansible.builtin.include_tasks: prerequisites.yml
  when: >
    chrony_role_action in ['all', 'prerequisites']
  tags:
    - chrony_setup
    - chrony_requirements

- name: Chrony | install | Install Chrony package
  ansible.builtin.include_tasks: install.yml
  when: >
    chrony_role_action in ['all', 'install']
  tags:
    - chrony_setup
    - chrony_install

- name: Chrony | configure | Configure Chrony service
  ansible.builtin.include_tasks: configure.yml
  when: >
    chrony_role_action in ['all', 'configure']
  tags:
    - chrony_setup
    - chrony_configure

- name: Chrony | logrotate | Configure logrotate for Chrony service
  ansible.builtin.include_tasks: logrotate.yml
  when: >
    chrony_role_action in ['all', 'configure', 'logrotate'] and
    chrony_configure_logrotate | default(false)
  tags:
    - chrony_config
    - chrony_logrotate

- name: Chrony | upgrade | Upgrade Chrony package
  ansible.builtin.include_tasks: upgrade.yml
  when: >
    chrony_role_action in ['upgrade']
  tags:
    - chrony_upgrade

- name: Chrony | test | Verify time synchronization
  ansible.builtin.include_tasks: test.yml
  when: >
    chrony_role_action in ['all', 'configure', 'logrotate', 'upgrade' ] and
    chrony_run_test | default(false)
  tags:
    - chrony_test
    - chrony_verify
