---
- name: Chrony | prerequisites | Check if NTP service exists
  ansible.builtin.systemd:
    name: "{{ __chrony_ntp_service_name }}"
  register: __chrony_ntp_service_check
  failed_when: false
  check_mode: true

- name: Chrony | prerequisites | Stop and disable NTP service if running
  become: true
  ansible.builtin.systemd:
    name: "{{ __chrony_ntp_service_name }}"
    state: stopped
    enabled: false
    daemon_reload: true
  when: >
    not ansible_check_mode and
    __chrony_ntp_service_check.status is defined and
    __chrony_ntp_service_check.status.ActiveState in ['active', 'activating']

- name: Chrony | prerequisites | Check if systemd-timesyncd service exists
  ansible.builtin.systemd:
    name: "{{ __chrony_timesyncd_service_name }}"
  register: __chrony_timesyncd_check
  failed_when: false
  check_mode: true

- name: Chrony | prerequisites | Stop and disable systemd-timesyncd service if running
  become: true
  ansible.builtin.systemd:
    name: "{{ __chrony_timesyncd_service_name }}"
    state: stopped
    enabled: false
    daemon_reload: true
  when: >
    not ansible_check_mode and
    __chrony_timesyncd_check.status is defined and
    __chrony_timesyncd_check.status.ActiveState in ['active', 'activating']
