---
- name: Chrony | test | Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Chrony | test | Force NTP sync
  become: true
  ansible.builtin.command: chronyc makestep
  register: __chrony_makestep_result
  changed_when:
    - __chrony_makestep_result.rc == 0
    - "'200 OK' in __chrony_makestep_result.stdout"
    - "'Clock was stepped' in __chrony_makestep_result.stdout or 'stepped' in __chrony_makestep_result.stdout.lower()"
  failed_when:
    - __chrony_makestep_result.rc != 0
    - "'not synchronised' not in __chrony_makestep_result.stdout.lower()"
    - "'no suitable source' not in __chrony_makestep_result.stdout.lower()"

- name: Chrony | test | Ensure system is NTP time synced
  ansible.builtin.command: chronyc waitsync 30
  changed_when: false

- name: Chrony | test | Check if time is synchronized with server
  ansible.builtin.command: chronyc tracking
  changed_when: false
  failed_when: __chrony_tracking_result.rc != 0
  register: __chrony_tracking_result

- name: Chrony | test | Show tracking details
  ansible.builtin.debug:
    msg: >
      Tracking Output:
      {{ __chrony_tracking_result.stdout_lines | join('\n') }}
