---
# =============================================================================
# Ansible Role: Chrony - Tasks: Upgrade
# =============================================================================
# Upgrade Chrony packages to the latest version.
# =============================================================================

- name: Chrony | upgrade | Upgrade Chrony package to the latest version # noqa: package-latest
  become: true
  notify: restart chrony
  ansible.builtin.package:
    name: "{{ __chrony_package_name }}"
    state: latest
    update_cache: true
