---
# Handler variables:
#   __chrony_service_name - internal, set per-OS in vars/
#   chrony_service_enabled - user-configurable default

- name: Chrony | handlers | Restart Chrony service
  become: true
  ansible.builtin.systemd:
    name: "{{ __chrony_service_name }}"
    state: restarted
    daemon_reload: true
    enabled: "{{ chrony_service_enabled }}"
  listen: "restart chrony"
