---
# =============================================================================
# Ansible Role: Chrony - Handlers
# =============================================================================
# Handlers for service management operations.
# =============================================================================

- name: Chrony | handlers | Restart Chrony service
  become: true
  ansible.builtin.systemd:
    name: "{{ __chrony_service_name }}"
    state: restarted
    daemon_reload: true
    enabled: "{{ chrony_service_enabled }}"
  listen: "restart chrony"
