---
- name: molecule | Prepare
  hosts: all
  gather_facts: false
  become: true

  tasks:
    - name: Prepare | Fix /etc/shadow permissions
      ansible.builtin.file:
        path: /etc/shadow
        mode: "0400"

    - name: Prepare | Ensure /etc/chrony directory exists
      ansible.builtin.file:
        path: /etc/chrony
        state: directory
        mode: "0755"
        owner: root
        group: root
      ignore_errors: true
